// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgcSgNtoVK3fLURrh-B_Dx1E026UtyQ8w',
    appId: '1:1836475697:web:48dd8bd9082ab769befc10',
    messagingSenderId: '1836475697',
    projectId: 'e-spend-a116b',
    authDomain: 'e-spend-a116b.firebaseapp.com',
    storageBucket: 'e-spend-a116b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfxbYbRZ4VYYoF1bs_iN21WvqoqbGH__A',
    appId: '1:1836475697:android:102a0678250a8fb0befc10',
    messagingSenderId: '1836475697',
    projectId: 'e-spend-a116b',
    storageBucket: 'e-spend-a116b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCymhEgKUQ1hUgKPjWt3sdLmDfUlp3sGIA',
    appId: '1:1836475697:ios:5259ac2209a41292befc10',
    messagingSenderId: '1836475697',
    projectId: 'e-spend-a116b',
    storageBucket: 'e-spend-a116b.appspot.com',
    iosClientId: '1836475697-7cnltr2h16k80ot6608bpo0mqac5ach2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterESpend',
  );
}
